apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-service
  namespace: trading-sim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-service
  template:
    metadata:
      labels:
        app: market-service
    spec:
      containers:
        - name: market-service
          image: trading-simulator-market-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: trading-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: ALPHAVANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: trading-secrets
                  key: ALPHAVANTAGE_API_KEY
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: market-service
  namespace: trading-sim
spec:
  selector:
    app: market-service
  ports:
    - port: 8081
      targetPort: 8081
